arb-dir: lib/src/localization
output-dir: lib/src/localization/gen
template-arb-file: module_en.arb
output-localization-file: shared_localizations.dart
output-class: SharedLocs
synthetic-package: false
nullable-getter: false
